services:
  # Database Service (Postgres)
  postgres:
    # Use the Docker Image postgres. This will pull the latest version.
    image: 'postgres:latest'
    # Give the container the name postgres-db. You can change to something else.
    container_name: postgres-db
    # Set up the database name, username and password. You can change these values.
    environment:
      - 'POSTGRES_DB=demoDB'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    # Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
